### ISSUE TITLE
spreadsheet map updates

### ISSUE THREAD

**Issue by hawc2** [phillycommunitywireless/pcwnetworkmap#1]
make map depend on a live google sheet. editing the geojson is difficult, would be ideal to pull data from a spreadsheet we can update with relevant info

**Comment by dzygmundfelt** [comment]
How does this get built and deployed?

**Comment by dzygmundfelt** [comment]
Some context/notes:

[The other PCW map used gatsby](https://github.com/phillycommunitywireless/map/blob/main/gatsby-config.js), and there was a plug-in for pulling data from google sheets.

According to a popular AI tool, here's a Google Apps Script we could use that would trigger a github action 
```
function onEdit(e) {
  var sheet = e.source.getSheetByName('YourSheetName'); // Change to your sheet name
  var range = e.range;
  
  // Check if the edited cell is in a specific range
  if (range.getColumn() == 1 && range.getRow() == 1) {
    // Trigger the GitHub Action webhook
    var webhookURL = 'https://api.github.com/repos/your_username/your_repo/dispatches';
    
    var options = {
      method: 'post',
      headers: {
        'Authorization': 'Bearer YOUR_GITHUB_TOKEN', // Generate a GitHub token with repo access
        'Content-Type': 'application/json',
        'User-Agent': 'Mozilla/4.0 (compatible; Google Apps Script)',
      },
      payload: JSON.stringify({
        event_type: 'google_sheet_updated',
      }),
    };
    
    UrlFetchApp.fetch(webhookURL, options);
  }
}
```
and here's a github action to go into `.github/workflows` that'd use it
```
name: Google Sheets Trigger

on:
  repository_dispatch:
    types: [google_sheet_updated]

jobs:
  update_data:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Your Build and Deploy Steps
        run: |
          # Add your build and deploy steps here

```
We'd need to create a new project in Google and add the sheet with the data to it, I think.
